### ISSUE TITLE
Add DB Support

### ISSUE THREAD

**Issue by x9nico** [komiss77/ArmorStandTools#1]
Hi, can you add an option in config for connect the plugin to my DB (MySQL) ?

I'm running a network with multiples Hubs servers, it could be cool to add this :)

**Comment by komiss77** [comment]
I am at a loss to decide which data should be stored in the Mysql? This is a tools plugin for generating and configuring AS, and there is nothing besides the configuration file.

**Comment by x9nico** [comment]
Coordinates of ArmorStands who are set with their rotation (X,Y,Z), equipment...

**Comment by x9nico** [comment]
If you want, I want sync my armorstands accross my multi-hubs :)

**Comment by komiss77** [comment]
I just keep this tool in working order for new version of spigot. Your request is too specific, greatly complicates the plugin code and configuration, and is unnecessary for most users. In your case, it is easier to use the update the world files for all lobbies from the update folder via .sh, or use Rcon to generate racks (the plugin issues a command to generate)
