### ISSUE TITLE
Lock Equipment Slots Option

### ISSUE THREAD

**Issue by calypsocz** [komiss77/ArmorStandTools#2]
Hi, Is there a way to add option to lock equipment slots?
Thx in advance!
- Calypso

**Comment by komiss77** [comment]
There was a problem with defining nms fields for future compatibility, but i try to fix this in 4.3 update. 
https://www.spigotmc.org/resources/armor-stand-tools-reborn.82724/download?version=366644

**Comment by calypsocz** [comment]
Love to head that!
Keep the good work!
